#include <stddef.h>
#include <stdint.h>
#include <string.h>

#include <FreeRTOS.h>
#include <task.h>

#include "c6x.h"

/*
 * TLS emulation object.
 *
 * The definition of this object must match that of the compiler for this target.
 */
struct __emutls_object
{
	const uint8_t *pTmplAddr;
};

/*
 * Get the task-specific address of a TLS variable.
 *
 * Calls to this function are generated by the compiler whenever a __thread
 * variable is accessed.
 */
void *__tls_get_address( const struct __emutls_object *pTlsCtrlVar );

#if configTLS_DATA_SIZE != 0
	/* Start address of the TLS template section. */
	extern const uint8_t __tls_tmpl_start[];

	/* End address of the TLS template section. */
	extern const uint8_t __tls_tmpl_end[];
#endif // configTLS_DATA_SIZE

/*
 * Set up the system timer interrupt.
 */
static void portSetupTimerInterrupt( void )
{
	// TODO Set up hardware timer.
}

/*
 * Task entry point.
 */
static void vPortTaskEntry( TaskFunction_t fn, void *pArg )
{
	portENABLE_INTERRUPTS();

	fn( pArg );

	vTaskDelete( NULL );
}

/*
 * Initialize the stack of a task in a state suitable for context restoration.
 */
StackType_t *pxPortInitialiseStack(StackType_t *pTopOfStack, TaskFunction_t fn, void *pArg)
{
	/* C6000 EABI mandates that the stack pointer be 8-byte aligned. */
	assert(((uint32_t)pTopOfStack & (((uint32_t)1 << 3) - 1)) == 0);

	/* The C6000 EABI mandates that the stack pointer always be 8-byte aligned. In addition,
	it requires that the 4 byte word at the stack pointer be available on a function call
	threshold. As a result, reserve 8 bytes to comply with those requirements. */

	/* See C6000 Embedded Application Binary Interface - 4.4 Frame Layout. */
	*( --pTopOfStack ) = 0;
	*( --pTopOfStack ) = 0;

	/* A15:A14 */
	*( --pTopOfStack ) = 15;
	*( --pTopOfStack ) = 14;

	/* A1:A0 */
	*( --pTopOfStack ) = 1;
	*( --pTopOfStack ) = 0;

	*( --pTopOfStack ) = 1;
	*( --pTopOfStack ) = 0;

	/* A3:A2 */
	*( --pTopOfStack ) = 3;
	*( --pTopOfStack ) = 2;

	*( --pTopOfStack ) = 3;
	*( --pTopOfStack ) = 2;

	/* A5:A4 */
	*( --pTopOfStack ) = 5;
	*( --pTopOfStack ) = ( StackType_t ) fn;

	*( --pTopOfStack ) = 5;
	*( --pTopOfStack ) = ( StackType_t ) pArg;

	/* A7:A6 */
	*( --pTopOfStack ) = 7;
	*( --pTopOfStack ) = 6;

	*( --pTopOfStack ) = 7;
	*( --pTopOfStack ) = 6;

	/* A9:A8 */
	*( --pTopOfStack ) = 9;
	*( --pTopOfStack ) = 8;

	*( --pTopOfStack ) = 9;
	*( --pTopOfStack ) = 8;

	/* A11:A10 */
	*( --pTopOfStack ) = 11;
	*( --pTopOfStack ) = 10;

	*( --pTopOfStack ) = 11;
	*( --pTopOfStack ) = 10;

	/* A13:A12 */
	*( --pTopOfStack ) = 13;
	*( --pTopOfStack ) = 12;

	*( --pTopOfStack ) = 13;
	*( --pTopOfStack ) = 12;

	/* A17:A16 */
	*( --pTopOfStack ) = 17;
	*( --pTopOfStack ) = 16;

	*( --pTopOfStack ) = 17;
	*( --pTopOfStack ) = 16;

	/* A19:A18 */
	*( --pTopOfStack ) = 19;
	*( --pTopOfStack ) = 18;

	*( --pTopOfStack ) = 19;
	*( --pTopOfStack ) = 18;

	/* A21:A20 */
	*( --pTopOfStack ) = 21;
	*( --pTopOfStack ) = 20;

	*( --pTopOfStack ) = 21;
	*( --pTopOfStack ) = 20;

	/* A23:A22 */
	*( --pTopOfStack ) = 23;
	*( --pTopOfStack ) = 22;

	*( --pTopOfStack ) = 23;
	*( --pTopOfStack ) = 22;

	/* A25:A24 */
	*( --pTopOfStack ) = 25;
	*( --pTopOfStack ) = 24;

	*( --pTopOfStack ) = 25;
	*( --pTopOfStack ) = 24;

	/* A27:A26 */
	*( --pTopOfStack ) = 27;
	*( --pTopOfStack ) = 26;

	*( --pTopOfStack ) = 27;
	*( --pTopOfStack ) = 26;

	/* A29:A28 */
	*( --pTopOfStack ) = 29;
	*( --pTopOfStack ) = 28;

	*( --pTopOfStack ) = 29;
	*( --pTopOfStack ) = 28;

	/* A31:A30 */
	*( --pTopOfStack ) = 31;
	*( --pTopOfStack ) = 30;

	*( --pTopOfStack ) = 31;
	*( --pTopOfStack ) = 30;

	*( --pTopOfStack ) = 0; /* FAUCR */
	*( --pTopOfStack ) = 0; /* FMCR */

	*( --pTopOfStack ) = 0; /* NTSR */
	*( --pTopOfStack ) = 0; /* ILC */

	*( --pTopOfStack ) = 0; /* ignored */
	*( --pTopOfStack ) = ( StackType_t ) vPortTaskEntry; /* NRP */

	*( --pTopOfStack ) = 0; /* FADCR */
	*( --pTopOfStack ) = 0; /* RILC */

	return pTopOfStack;
}

/*
 * Start the scheduler.
 */
portBASE_TYPE xPortStartScheduler( void )
{
	void vPortStartFirstTask( void );

	portSetupTimerInterrupt();
	vPortStartFirstTask();

	/* Should never be reached. */
	return pdTRUE;
}

/*
 * End the scheduler.
 *
 * The scheduler never stops. This function exists only to avoid link errors.
 */
void vPortEndScheduler(void)
{
}

#if ( configTLS_DATA_SIZE != 0 )

	void vPortInitialiseTlsData( void *pTlsData )
	{
	uint8_t *pTlsDataBytes = pTlsData;
	size_t size;

		configASSERT( pTlsData );
		configASSERT( ( ( uintptr_t ) pTlsData & 7 ) == 0 );

		size = __tls_tmpl_end - __tls_tmpl_start;
		configASSERT( size <= ( size_t ) configTLS_DATA_SIZE );

		memcpy( pTlsDataBytes, __tls_tmpl_start, size );
		memset( &pTlsDataBytes[ size ], 0, configTLS_DATA_SIZE - size );
	}

	void *__tls_get_address( const struct __emutls_object *pTlsCtrlVar )
	{
	extern TaskHandle_t * volatile pxCurrentTCB;
	uint8_t *pxCurrentTCBBytes = ( uint8_t * ) pxCurrentTCB;
	uint8_t *pTlsData;

		pTlsData = &pxCurrentTCBBytes[ offsetof( StaticTask_t, ucDummy23 ) ];

		return &pTlsData[ pTlsCtrlVar->pTmplAddr - __tls_tmpl_start ];
	}

#endif /* configTLS_DATA_SIZE */
